[package]
name = "preprocess_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
preprocess_types = { path = "../preprocess_types" }
proc-macro2 = "1"
quote = "1"
regex = "1.6.0"
serde_json = "1"
syn = { version = "2", features = ["extra-traits"] }
